# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch: # allow manual reruns

jobs:
  ci:
    runs-on: ubuntu-latest

    # strategy:
    #   matrix:
    #     node-version: [20.x] # [14.x, 16.x, 18.x]
    #     # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Lint
        run: bun run lint --format junit -o reports/junit/js-lint-results.xml

      - name: Test
        run: bun run test
        env:
          CI: 1
          NODE_ENV: ci
          JEST_JUNIT_OUTPUT: "reports/junit/js-test-results.xml"
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          GOOGLE_SERVICE_ACCOUNT_EMAIL: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_EMAIL }}
          GOOGLE_SERVICE_ACCOUNT_KEY: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}

      - uses: actions/upload-artifact@v4
        with:
          name: reports
          path: reports/junit
      
      - uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage


